{
  "openapi": "3.0.0",
  "info": {
    "title": "Backend Project REST API",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://localhost:8080"
    }
  ],
  "components": {
    "securitySchemes": {
      "undefinedAuth": {
        "type": "http",
        "scheme": "basic"
      }
    }
  },
  "tags": [
    {
      "name": "customers"
    },
    {
      "name": "invoices"
    },
    {
      "name": "orders"
    },
    {
      "name": "order_details"
    },
    {
      "name": "products"
    },
    {
      "name": "sellers"
    },
    {
      "name": "stock_details"
    },
    {
      "name": "suppliers"
    }
  ],
  "paths": {
    "/rest/customers": {
      "get": {
        "tags": ["customers"],
        "summary": "all",
        "security": [
          {
            "undefinedAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/rest/customers/id/10": {
      "get": {
        "tags": ["customers"],
        "summary": "one(id)",
        "security": [
          {
            "undefinedAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "put": {
        "tags": ["customers"],
        "summary": "updateCustomer",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "name": "James",
                  "surname": "Bond",
                  "email": "007@domain.com"
                }
              }
            }
          }
        },
        "security": [
          {
            "undefinedAuth": []
          }
        ],
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "application/json"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/rest/customers/": {
      "post": {
        "tags": ["customers"],
        "summary": "newCustomer",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "name": "James",
                  "surname": "Clone",
                  "phoneNum": "3428782343",
                  "email": "007@domain.com",
                  "discountRate": 1,
                  "active": false
                }
              }
            }
          }
        },
        "security": [
          {
            "undefinedAuth": []
          }
        ],
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "application/json"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/rest/customers/id/11": {
      "delete": {
        "tags": ["customers"],
        "summary": "deleteCustomer",
        "security": [
          {
            "undefinedAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/rest/customers/q": {
      "get": {
        "tags": ["customers"],
        "summary": "getBy",
        "security": [
          {
            "undefinedAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/rest/invoices": {
      "get": {
        "tags": ["invoices"],
        "summary": "all",
        "security": [
          {
            "undefinedAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "post": {
        "tags": ["invoices"],
        "summary": "newInvoice",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "invoiceTimestamp": 1760561853000,
                  "dueTimestamp": 1794880000000,
                  "subTotal": 10,
                  "discount": 5,
                  "taxRate": 3,
                  "totalTax": 1.9,
                  "totalPrice": 11.1
                }
              }
            }
          }
        },
        "security": [
          {
            "undefinedAuth": []
          }
        ],
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "application/json"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/rest/invoices/q": {
      "get": {
        "tags": ["invoices"],
        "summary": "getBy",
        "security": [
          {
            "undefinedAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/rest/invoices/id/6": {
      "get": {
        "tags": ["invoices"],
        "summary": "one(id)",
        "security": [
          {
            "undefinedAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "delete": {
        "tags": ["invoices"],
        "summary": "deleteInvoice",
        "security": [
          {
            "undefinedAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/rest/invoices/id/4": {
      "put": {
        "tags": ["invoices"],
        "summary": "updateInvoice",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "invoiceTimestamp": 1660561814000,
                  "dueTimestamp": 1663333200000,
                  "discount": 10,
                  "taxRate": 1,
                  "subTotal": 10000
                }
              }
            }
          }
        },
        "security": [
          {
            "undefinedAuth": []
          }
        ],
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "application/json"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/rest/orders/": {
      "get": {
        "tags": ["orders"],
        "summary": "all",
        "security": [
          {
            "undefinedAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "post": {
        "tags": ["orders"],
        "summary": "newOrder",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "invoice": {
                    "invoiceTimestamp": "2021-06-13 11:00:11",
                    "dueTimestamp": "2021-08-11 13:00:11",
                    "subTotal": 119.4,
                    "discount": 10,
                    "taxRate": 8,
                    "totalTax": 9.55,
                    "totalPrice": 118.95
                  },
                  "timestamp": "2021-06-12 12:00:11.0"
                }
              }
            }
          }
        },
        "security": [
          {
            "undefinedAuth": []
          }
        ],
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "application/json"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/rest/orders/q": {
      "get": {
        "tags": ["orders"],
        "summary": "getBy",
        "security": [
          {
            "undefinedAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/rest/orders/id/7": {
      "get": {
        "tags": ["orders"],
        "summary": "one(id)",
        "security": [
          {
            "undefinedAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "put": {
        "tags": ["orders"],
        "summary": "updateOrder",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "timestamp": 1650554004000
                }
              }
            }
          }
        },
        "security": [
          {
            "undefinedAuth": []
          }
        ],
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "application/json"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/rest/orders/id/8": {
      "delete": {
        "tags": ["orders"],
        "summary": "deleteOrder",
        "security": [
          {
            "undefinedAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/rest/order_details": {
      "get": {
        "tags": ["order_details"],
        "summary": "all",
        "security": [
          {
            "undefinedAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/rest/order_details/q": {
      "get": {
        "tags": ["order_details"],
        "summary": "getBy",
        "security": [
          {
            "undefinedAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/rest/order_details/id/11": {
      "get": {
        "tags": ["order_details"],
        "summary": "one(id)",
        "security": [
          {
            "undefinedAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "delete": {
        "tags": ["order_details"],
        "summary": "deleteOrderDetail",
        "security": [
          {
            "undefinedAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/rest/order_details/": {
      "post": {
        "tags": ["order_details"],
        "summary": "newOrderDetail",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "quantity": 123
                }
              }
            }
          }
        },
        "security": [
          {
            "undefinedAuth": []
          }
        ],
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "application/json"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/rest/order_details/id/1": {
      "put": {
        "tags": ["order_details"],
        "summary": "updateOrderDetail",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "quantity": 123
                }
              }
            }
          }
        },
        "security": [
          {
            "undefinedAuth": []
          }
        ],
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "application/json"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/rest/products/": {
      "get": {
        "tags": ["products"],
        "summary": "all",
        "security": [
          {
            "undefinedAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "post": {
        "tags": ["products"],
        "summary": "newProduct",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "categoryName": "Ayran",
                  "name": "Tombul Ayran 293ml",
                  "unitPrice": 6.75,
                  "active": true
                }
              }
            }
          }
        },
        "security": [
          {
            "undefinedAuth": []
          }
        ],
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "application/json"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/rest/products/id/12": {
      "get": {
        "tags": ["products"],
        "summary": "one(id)",
        "security": [
          {
            "undefinedAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "put": {
        "tags": ["products"],
        "summary": "updateProduct",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "categoryName": "Ayran",
                  "active": false
                }
              }
            }
          }
        },
        "security": [
          {
            "undefinedAuth": []
          }
        ],
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "application/json"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "delete": {
        "tags": ["products"],
        "summary": "deleteProduct",
        "security": [
          {
            "undefinedAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/rest/products/q": {
      "get": {
        "tags": ["products"],
        "summary": "getBy",
        "security": [
          {
            "undefinedAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/rest/sellers": {
      "get": {
        "tags": ["sellers"],
        "summary": "all",
        "security": [
          {
            "undefinedAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "post": {
        "tags": ["sellers"],
        "summary": "newSeller",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "address": "Demo mah. demo sokak demo evleri",
                  "phoneNum": "55555555",
                  "name": "Demo2",
                  "email": "demo2@domain.com",
                  "fax": "",
                  "active": false
                }
              }
            }
          }
        },
        "security": [
          {
            "undefinedAuth": []
          }
        ],
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "application/json"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/rest/sellers/id/10": {
      "get": {
        "tags": ["sellers"],
        "summary": "one(id)",
        "security": [
          {
            "undefinedAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "put": {
        "tags": ["sellers"],
        "summary": "updateSeller",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "name": "Demonew",
                  "active": true
                }
              }
            }
          }
        },
        "security": [
          {
            "undefinedAuth": []
          }
        ],
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "application/json"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "delete": {
        "tags": ["sellers"],
        "summary": "deleteSeller",
        "security": [
          {
            "undefinedAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/rest/sellers/q": {
      "get": {
        "tags": ["sellers"],
        "summary": "getBy",
        "security": [
          {
            "undefinedAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/rest/stock_details": {
      "get": {
        "tags": ["stock_details"],
        "summary": "all",
        "security": [
          {
            "undefinedAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/rest/stock_details/q": {
      "get": {
        "tags": ["stock_details"],
        "summary": "getBy",
        "security": [
          {
            "undefinedAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/rest/stock_details/id/2": {
      "get": {
        "tags": ["stock_details"],
        "summary": "one(id)",
        "security": [
          {
            "undefinedAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "put": {
        "tags": ["stock_details"],
        "summary": "updateStockDetail",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "quantity": 123
                }
              }
            }
          }
        },
        "security": [
          {
            "undefinedAuth": []
          }
        ],
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "application/json"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "delete": {
        "tags": ["stock_details"],
        "summary": "deleteStockDetail",
        "security": [
          {
            "undefinedAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/rest/stock_details/": {
      "post": {
        "tags": ["stock_details"],
        "summary": "newStockDetail",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "quantity": 1977
                }
              }
            }
          }
        },
        "security": [
          {
            "undefinedAuth": []
          }
        ],
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "application/json"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/rest/suppliers": {
      "get": {
        "tags": ["suppliers"],
        "summary": "all",
        "security": [
          {
            "undefinedAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/rest/suppliers/q": {
      "get": {
        "tags": ["suppliers"],
        "summary": "getBy",
        "security": [
          {
            "undefinedAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/rest/suppliers/id/8": {
      "get": {
        "tags": ["suppliers"],
        "summary": "one(id)",
        "security": [
          {
            "undefinedAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "put": {
        "tags": ["suppliers"],
        "summary": "updateSupplier",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "active": true
                }
              }
            }
          }
        },
        "security": [
          {
            "undefinedAuth": []
          }
        ],
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "application/json"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "delete": {
        "tags": ["suppliers"],
        "summary": "deleteSupplier",
        "security": [
          {
            "undefinedAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/rest/suppliers/": {
      "post": {
        "tags": ["suppliers"],
        "summary": "newSupplier",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "name": "demo",
                  "address": "Demo adres",
                  "phoneNum": "1234567876",
                  "active": false
                }
              }
            }
          }
        },
        "security": [
          {
            "undefinedAuth": []
          }
        ],
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "application/json"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    }
  }
}
